# Cloud Build Configuration for Production Deployments
# This file is used as a template for creating tenant-specific production triggers

name: deploy-${_TENANT_ID}-production
description: Auto-deploy to production on push to main branch

# Trigger configuration
trigger:
  github:
    owner: ${_GITHUB_OWNER}
    name: ${_GITHUB_REPO}
    push:
      branch: ^main$

# Build steps
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:latest'
      - '.'

  # Step 2: Push versioned image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:${SHORT_SHA}'

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:latest'

  # Step 4: Deploy to Cloud Run (Production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_TENANT_ID}-website'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'TENANT_ID=${_TENANT_ID},ENVIRONMENT=production,GATEWAY_URL=${_GATEWAY_URL}'
      - '--set-labels'
      - 'tenant_id=${_TENANT_ID},environment=production,cost_center=clearforge_services,service_type=website'

  # Step 5: Update Firestore deployment record
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud firestore documents update tenants/${_TENANT_ID} \
          --update-mask deployment.last_production_deploy \
          --field-data "{\"last_production_deploy\":{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"commit\":\"${SHORT_SHA}\",\"branch\":\"main\",\"build_id\":\"${BUILD_ID}\"}}"

# Substitutions (variables)
substitutions:
  _TENANT_ID: 'example_tenant_001'  # Replaced dynamically
  _GITHUB_OWNER: 'clearforge'       # Replaced dynamically
  _GITHUB_REPO: 'example-repo'      # Replaced dynamically
  _GATEWAY_URL: 'https://xynergy-intelligence-gateway-xxx.run.app'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  timeout: '1200s'  # 20 minutes

# Images to be stored in Container Registry
images:
  - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_TENANT_ID}-website:latest'
