# Cloud Build configuration for DEV environment
# Triggered on push to main branch
#
# Setup trigger:
# gcloud builds triggers create github \
#   --name="gateway-dev-deploy" \
#   --repo-name="xynergy-core" \
#   --repo-owner="your-org" \
#   --branch-pattern="^main$" \
#   --build-config="xynergyos-intelligence-gateway/cloudbuild-dev.yaml" \
#   --included-files="xynergyos-intelligence-gateway/**" \
#   --project=xynergy-dev-1757909467

steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    dir: 'xynergyos-intelligence-gateway'

  # Run TypeScript compilation
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'xynergyos-intelligence-gateway'

  # Build Docker image with multi-tagging
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xynergy-services/xynergyos-intelligence-gateway:dev'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xynergy-services/xynergyos-intelligence-gateway:dev-$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xynergy-services/xynergyos-intelligence-gateway:dev-$BUILD_ID'
      - '.'
    dir: 'xynergyos-intelligence-gateway'

  # Push all tags to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xynergy-services/xynergyos-intelligence-gateway'

  # Deploy to Cloud Run (DEV)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'xynergyos-intelligence-gateway'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/xynergy-services/xynergyos-intelligence-gateway:dev-$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production,XYNERGY_ENV=dev,MOCK_MODE=true'
      - '--set-secrets=JWT_SECRET=jwt-secret-dev:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      - '--vpc-connector=redis-connector'
      - '--vpc-egress=private-ranges-only'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s' # 20 minutes

# Substitutions (optional - for manual triggers)
substitutions:
  _SERVICE_NAME: 'xynergyos-intelligence-gateway'
  _REGION: 'us-central1'
